### ISSUE TITLE
Compare Fonts script?

### ISSUE THREAD

**Issue by gorjious** [weiweihuanghuang/wei-glyphs-scripts#5]
Hi Wei, I was searching in the Glyphs plugin manager scripts and came across your Compare Fonts script but looks like it's not in your repo anymore. 

Any chance it is still available?

<img width="782" alt="Screenshot 2022-10-13 at 15 01 14" src="https://user-images.githubusercontent.com/23149420/195727630-5dc778ef-439e-4db2-981d-a7d1f854e0ab.png">

**Comment by weiweihuanghuang** [comment]
Hey I removed it since the functionality exists now in Glyphs App, under Edit > Compare Fonts

**Comment by gorjious** [comment]
I've been trying out the Edit > Compare Fonts too but what I find tedious is manually selecting matching sources and then going through to see which glyphs are different. I like that your script (if I am understanding it correctly) immediately provides a new tab with all the glyphs in their respective sources which are different.

**Comment by weiweihuanghuang** [comment]
Fair enough, that's totally why I made the script 😅
I've uploaded it again.

**Comment by gorjious** [comment]
haha. thank you! i'll give it a spin tomorrow.
